#!/usr/bin/env python3
"""Export the tiny CIFAR-10 CNN artifact into firmware C headers.

Re-runs the independent reference, then emits the INT8 conv/fc weights, the
requantized biases, the fixed-point multipliers and the retained quantized test
subset as C headers plus a hash-bound manifest.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import cifar_reference as reference


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def c_array(ctype: str, name: str, values: list[int], per_line: int) -> str:
    lines = [f"static const {ctype} {name}[{len(values)}] = {{"]
    for start in range(0, len(values), per_line):
        lines.append("    " + ", ".join(str(v) for v in values[start:start + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("model", type=Path)
    parser.add_argument("--header-dir", type=Path, default=Path("software/benchmarks"))
    parser.add_argument("--manifest", type=Path, default=Path("build/cifar/export.json"))
    args = parser.parse_args()

    result = reference.reference(args.model)
    model = json.loads(args.model.read_text())
    conv, fc, test = model["conv"], model["fc"], model["test"]
    height = model["input"]["height"]
    kernel = conv["kernel"]
    k_dim = 3 * kernel * kernel
    oc = conv["out_channels"]
    # NPU B layout: B[k][n] = weight[n][k].
    conv_b = [0] * (k_dim * oc)
    for n in range(oc):
        for k in range(k_dim):
            conv_b[k * oc + n] = conv["weights"][n * k_dim + k]

    model_header = [
        "// Generated by scripts/cifar_export.py. Do not edit.",
        f"// model hash {model['hash']}",
        "#ifndef CIFAR_MODEL_H",
        "#define CIFAR_MODEL_H",
        "#include <stdint.h>",
        "",
        f"#define CIFAR_H {height}u",
        f"#define CIFAR_OH {height - conv['kernel'] + 1}u",
        f"#define CIFAR_CONV_OUT {conv['out_channels']}u",
        f"#define CIFAR_CONV_KERNEL {conv['kernel']}u",
        f"#define CIFAR_CONV_K {(3 * conv['kernel'] * conv['kernel'])}u",
        f"#define CIFAR_FC_IN {fc['in_features']}u",
        f"#define CIFAR_FC_OUT {fc['out_features']}u",
        f"#define CIFAR_CONV_MULT {conv['requant']['mult']}",
        f"#define CIFAR_CONV_SHIFT {conv['requant']['shift']}",
        f"#define CIFAR_FC_MULT {fc['requant']['mult']}",
        f"#define CIFAR_FC_SHIFT {fc['requant']['shift']}",
        f'#define CIFAR_MODEL_HASH "{model["hash"]}"',
        "",
        c_array("int8_t", "cifar_conv_weights", conv["weights"], 16),
        "",
        c_array("int8_t", "cifar_conv_weights_b", conv_b, 16),
        "",
        c_array("int32_t", "cifar_conv_bias_q", conv["bias_q"], 8),
        "",
        c_array("int8_t", "cifar_fc_weights", fc["weights"], 16),
        "",
        c_array("int32_t", "cifar_fc_bias_q", fc["bias_q"], 8),
        "",
        "#endif",
        "",
    ]
    images_header = [
        "// Generated by scripts/cifar_export.py. Do not edit.",
        f"// model hash {model['hash']}",
        "#ifndef CIFAR_IMAGES_H",
        "#define CIFAR_IMAGES_H",
        "#include <stdint.h>",
        "",
        f"#define CIFAR_TEST_COUNT {len(test['labels'])}u",
        "",
        c_array("int8_t", "cifar_test_images", test["images"], 24),
        "",
        c_array("uint8_t", "cifar_test_labels", test["labels"], 16),
        "",
        c_array("uint8_t", "cifar_test_classes", test["reference_classes"], 16),
        "",
        c_array("int8_t", "cifar_test_logits", [v for row in test["reference_logits"] for v in row], 16),
        "",
        "#endif",
        "",
    ]
    model_header_path = args.header_dir / "cifar_model.h"
    images_header_path = args.header_dir / "cifar_images.h"
    model_header_path.write_text("\n".join(model_header))
    images_header_path.write_text("\n".join(images_header))
    manifest = {"schema": "aster.cifar.export.v1", "model_hash": model["hash"], "reference": result,
                "headers": {"cifar_model.h": sha256(model_header_path),
                            "cifar_images.h": sha256(images_header_path)},
                "test_count": len(test["labels"])}
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    print(f"PASS: exported {model_header_path} and {images_header_path} "
          f"({manifest['test_count']} images, reference {result['accuracy']:.4f})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
