#!/usr/bin/env python3
"""Export the tiny CIFAR-10 CNN (v2) artifact into firmware C headers."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import cifar_reference as reference


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def c_array(ctype: str, name: str, values: list[int], per_line: int) -> str:
    lines = [f"static const {ctype} {name}[{len(values)}] = {{"]
    for start in range(0, len(values), per_line):
        lines.append("    " + ", ".join(str(v) for v in values[start:start + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


def npu_b(layer: dict) -> list[int]:
    k_dim = layer["in_channels"] * layer["kernel"] * layer["kernel"]
    out_channels = layer["out_channels"]
    layout = [0] * (k_dim * out_channels)
    for n in range(out_channels):
        for k in range(k_dim):
            layout[k * out_channels + n] = layer["weights"][n * k_dim + k]
    return layout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("model", type=Path)
    parser.add_argument("--header-dir", type=Path, default=Path("software/benchmarks"))
    parser.add_argument("--manifest", type=Path, default=Path("build/cifar/export.json"))
    args = parser.parse_args()

    result = reference.reference(args.model)
    model = json.loads(args.model.read_text())
    c1, c2, fc, test = model["conv1"], model["conv2"], model["fc"], model["test"]

    model_header = [
        "// Generated by scripts/cifar_export.py. Do not edit.",
        f"// model hash {model['hash']}",
        "#ifndef CIFAR_MODEL_H",
        "#define CIFAR_MODEL_H",
        "#include <stdint.h>",
        "",
        "#define CIFAR_H 16u",
        f"#define CIFAR_CONV1_OUT {c1['out_channels']}u",
        f"#define CIFAR_CONV1_K {c1['in_channels'] * 9}u",
        f"#define CIFAR_CONV2_OUT {c2['out_channels']}u",
        f"#define CIFAR_CONV2_K {c2['in_channels'] * 9}u",
        f"#define CIFAR_FC_IN {fc['in_features']}u",
        f"#define CIFAR_FC_OUT {fc['out_features']}u",
        f"#define CIFAR_CONV1_MULT {c1['requant']['mult']}",
        f"#define CIFAR_CONV1_SHIFT {c1['requant']['shift']}",
        f"#define CIFAR_CONV2_MULT {c2['requant']['mult']}",
        f"#define CIFAR_CONV2_SHIFT {c2['requant']['shift']}",
        f"#define CIFAR_FC_MULT {fc['requant']['mult']}",
        f"#define CIFAR_FC_SHIFT {fc['requant']['shift']}",
        f'#define CIFAR_MODEL_HASH "{model["hash"]}"',
        "",
        c_array("int8_t", "cifar_conv1_weights_b", npu_b(c1), 16),
        "",
        c_array("int32_t", "cifar_conv1_bias_q", c1["bias_q"], 8),
        "",
        c_array("int8_t", "cifar_conv2_weights_b", npu_b(c2), 16),
        "",
        c_array("int32_t", "cifar_conv2_bias_q", c2["bias_q"], 8),
        "",
        c_array("int8_t", "cifar_fc_weights", fc["weights"], 16),
        "",
        c_array("int32_t", "cifar_fc_bias_q", fc["bias_q"], 8),
        "",
        "#endif",
        "",
    ]
    images_header = [
        "// Generated by scripts/cifar_export.py. Do not edit.",
        f"// model hash {model['hash']}",
        "#ifndef CIFAR_IMAGES_H",
        "#define CIFAR_IMAGES_H",
        "#include <stdint.h>",
        "",
        f"#define CIFAR_TEST_COUNT {len(test['labels'])}u",
        "",
        c_array("int8_t", "cifar_test_images", test["images"], 24),
        "",
        c_array("uint8_t", "cifar_test_labels", test["labels"], 16),
        "",
        c_array("uint8_t", "cifar_test_classes", test["reference_classes"], 16),
        "",
        c_array("int8_t", "cifar_test_logits", [v for row in test["reference_logits"] for v in row], 16),
        "",
        "#endif",
        "",
    ]
    model_path = args.header_dir / "cifar_model.h"
    images_path = args.header_dir / "cifar_images.h"
    model_path.write_text("\n".join(model_header))
    images_path.write_text("\n".join(images_header))
    manifest = {"schema": "aster.cifar.export.v2", "model_hash": model["hash"], "reference": result,
                "headers": {"cifar_model.h": sha256(model_path), "cifar_images.h": sha256(images_path)},
                "test_count": len(test["labels"])}
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    print(f"PASS: exported {model_path} and {images_path} "
          f"({manifest['test_count']} images, reference {result['accuracy']:.4f})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
