#!/usr/bin/env python3
"""Bake a real PhysioNet MIT-BIH ECG segment for the streaming workload.

Decodes the MIT-BIH format-212 record, extracts a channel segment, centers it on
the ADC zero and quantizes to INT8. Emits the firmware header and a committed
JSON that the independent oracle reads, so firmware and oracle use identical
samples.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path

SOURCE = "https://physionet.org/files/mitdb/1.0.0/100.dat"
HEADER = "https://physionet.org/files/mitdb/1.0.0/100.hea"


def decode_212(buffer: bytes, samples: int) -> list[int]:
    out: list[int] = []
    for i in range(0, len(buffer) - 2, 3):
        b0, b1, b2 = buffer[i], buffer[i + 1], buffer[i + 2]
        first = b0 | ((b1 & 0x0F) << 8)
        second = (b1 >> 4) | (b2 << 4)
        if first & 0x800:
            first -= 0x1000
        if second & 0x800:
            second -= 0x1000
        out.append(first)
        out.append(second)
        if len(out) >= samples * 2:
            break
    return out


def round_half_away(value: float) -> int:
    return int(math.floor(value + 0.5)) if value >= 0 else -int(math.floor(-value + 0.5))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dat", type=Path, required=True, help="MIT-BIH record 100.dat")
    parser.add_argument("--channel", type=int, default=0)
    parser.add_argument("--start", type=int, default=0)
    parser.add_argument("--count", type=int, default=1024)
    parser.add_argument("--scale", type=int, default=4)
    parser.add_argument("--adc-zero", type=int, default=1024)
    parser.add_argument("--header", type=Path, default=Path("software/benchmarks/workload_ecg_data.h"))
    parser.add_argument("--json", type=Path, default=Path("docs/results/phase12/ecg_segment.json"))
    args = parser.parse_args()

    raw = args.dat.read_bytes()
    interleaved = decode_212(raw, args.start + args.count + 1)
    channel = interleaved[args.channel::2]
    if len(channel) < args.start + args.count:
        raise SystemExit("record shorter than the requested segment")
    centered = [value - args.adc_zero for value in channel[args.start:args.start + args.count]]
    quantized = [max(-128, min(127, round_half_away(value / args.scale))) for value in centered]
    samples = bytes((value & 0xFF) for value in quantized)

    args.header.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by scripts/gen_ecg_data.py. Do not edit.",
        f"// PhysioNet MIT-BIH Arrhythmia Database record 100, channel {args.channel},",
        f"// samples {args.start}..{args.start + args.count - 1}, ADC zero {args.adc_zero}, scale {args.scale}.",
        "#ifndef WORKLOAD_ECG_DATA_H",
        "#define WORKLOAD_ECG_DATA_H",
        "#include <stdint.h>",
        f"#define ECG_DATA_COUNT {args.count}",
        f"#define ECG_DATA_SCALE {args.scale}",
        f"static const int8_t ecg_samples[ECG_DATA_COUNT] = {{",
    ]
    for start in range(0, len(quantized), 16):
        lines.append("    " + ", ".join(str(v) for v in quantized[start:start + 16]) + ",")
    lines += ["};", "#endif", ""]
    args.header.write_text("\n".join(lines))

    segment = {
        "schema": "aster.ecg.segment.v1",
        "source": SOURCE, "header": HEADER, "record": "100",
        "channel": args.channel, "start": args.start, "count": args.count,
        "adc_zero": args.adc_zero, "scale": args.scale,
        "min": min(quantized), "max": max(quantized),
        "sha256": hashlib.sha256(samples).hexdigest(),
        "samples": quantized,
    }
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(segment, indent=2, sort_keys=True) + "\n")
    print(f"wrote {args.header} and {args.json} "
          f"({args.count} samples, range {min(quantized)}..{max(quantized)}, "
          f"sha256 {segment['sha256'][:16]})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
