#!/usr/bin/env python3
"""The CIFAR-10 CNN's images and convolution weights channels last (HWC), for 20.4's direct NPU method
(software/matrix/cifar.c): docs/npu.md's 19.3 clarification has Phase 20's CIFAR store "its images and weights
reordered at build time and write its pooled activations channels last, at no run-time cost". A kernel row is
then kw x C contiguous bytes, which the NPU's two-level A addressing reads as one segment.
  images   (y * 16 + x) * 3 + c                   (v1's: (c * 16 + y) * 16 + x)
  weights  B[k' * N + n], k' = (ky * 3 + kx) * C + c (v1's B: k = c * 9 + ky * 3 + kx)
Written from docs/results/workloads/cifar_model.json (its hash checked) to software/matrix/cifar_hwc.h;
`--check` compares the file with what it would write."""
import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "software/matrix/cifar_hwc.h"


def hwc_weights(layer: dict) -> list[int]:
    c_in, n_out, w = layer["in_channels"], layer["out_channels"], layer["weights"]
    k_dim = c_in * 9
    out = [0] * (k_dim * n_out)
    for n in range(n_out):
        for c in range(c_in):
            for ky in range(3):
                for kx in range(3):
                    out[((ky * 3 + kx) * c_in + c) * n_out + n] = w[n * k_dim + c * 9 + ky * 3 + kx]
    return out


def render() -> str:
    model = json.loads((ROOT / "docs/results/workloads/cifar_model.json").read_text())
    payload = json.dumps({k: v for k, v in model.items() if k != "hash"}, sort_keys=True).encode()
    if hashlib.sha256(payload).hexdigest() != model["hash"]:
        raise SystemExit("cifar_model.json's hash does not match its contents")
    images = model["test"]["images"]
    count = len(model["test"]["labels"])
    hwc = [images[i * 768 + (c * 16 + y) * 16 + x] for i in range(count) for y in range(16) for x in range(16)
           for c in range(3)]
    arrays = (("cifar_test_images_hwc", hwc), ("cifar_conv1_weights_hwc", hwc_weights(model["conv1"])),
              ("cifar_conv2_weights_hwc", hwc_weights(model["conv2"])))
    lines = ["// Generated by scripts/gen_cifar_hwc.py from docs/results/workloads/cifar_model.json; do not edit.",
             f"// The frozen model's test images and convolution weights, channels last (model hash {model['hash']}).",
             "#ifndef CIFAR_HWC_H", "#define CIFAR_HWC_H", "#include <stdint.h>"]
    for name, values in arrays:
        lines.append(f"static const int8_t {name}[{len(values)}] __attribute__((aligned(16))) = {{")
        for i in range(0, len(values), 24):
            lines.append("    " + ", ".join(str(v) for v in values[i:i + 24]) + ",")
        lines.append("};")
    lines.append("#endif")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        same = OUT.exists() and OUT.read_text() == text
        print(f"{'PASS' if same else 'FAIL'}: {OUT.relative_to(ROOT)} is what the model gives")
        return 0 if same else 1
    OUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
