#!/usr/bin/env python3
"""Seeded RV32I/M vectors, independently calculated using Python integers.

Reference: unprivileged ISA RV32I v2.1 and M v2.0. This is an integration
regression, not certification by the RISC-V architectural test suite.
"""
import argparse
from pathlib import Path
import random

MASK = 0xffffffff


def signed(value):
    value &= MASK
    return value if value < 0x80000000 else value - 0x100000000


def quotient(a, b):
    if b == 0:
        return -1
    q = abs(a) // abs(b)
    return -q if (a < 0) != (b < 0) else q


def evaluate(op, a, b):
    a, b = a & MASK, b & MASK
    sa, sb, shift = signed(a), signed(b), b & 31
    operations = {
        "add": lambda: a + b, "sub": lambda: a - b,
        "sll": lambda: a << shift, "srl": lambda: a >> shift,
        "sra": lambda: sa >> shift, "slt": lambda: int(sa < sb),
        "sltu": lambda: int(a < b), "xor": lambda: a ^ b,
        "or": lambda: a | b, "and": lambda: a & b,
        "mul": lambda: a * b, "mulh": lambda: (sa * sb) >> 32,
        "mulhsu": lambda: (sa * b) >> 32, "mulhu": lambda: (a * b) >> 32,
        "div": lambda: quotient(sa, sb),
        "divu": lambda: MASK if b == 0 else a // b,
        "rem": lambda: sa if b == 0 else sa - quotient(sa, sb) * sb,
        "remu": lambda: a if b == 0 else a % b,
        "beq": lambda: int(a == b), "bne": lambda: int(a != b),
        "blt": lambda: int(sa < sb), "bge": lambda: int(sa >= sb),
        "bltu": lambda: int(a < b), "bgeu": lambda: int(a >= b),
    }
    return operations[op]() & MASK


def generate(seed):
    rng = random.Random(seed)
    edge = [0, 1, MASK, 0x80000000, 0x7fffffff, 0xaaaa5555]
    pairs = [(a, b) for a in edge for b in edge]
    pairs += [(MASK, b) for b in (31, 32, 33, 255)]
    pairs += [(MASK - 6, 3), (7, MASK - 2)]
    pairs += [(rng.getrandbits(32), rng.getrandbits(32)) for _ in range(16)]
    lines = [f"# Generated by gen_rv32im_vectors.py; seed={seed}"]
    for op in "add sub sll slt sltu xor srl sra or and mul mulh mulhsu mulhu div divu rem remu".split():
        for a, b in pairs:
            lines.append(f"CHECK_R {op}, 0x{a:08x}, 0x{b:08x}, 0x{evaluate(op, a, b):08x}")
        for a, b in [(7, MASK - 2), (MASK, 0), (0x80000000, MASK), (0x80000000, 0x80000000)]:
            lines.append(f"CHECK_ALIAS {op}, 0x{a:08x}, 0x{b:08x}, 0x{evaluate(op, a, b):08x}")
    bases = dict(addi="add", slti="slt", sltiu="sltu", xori="xor", ori="or",
                 andi="and", slli="sll", srli="srl", srai="sra")
    for op, base in bases.items():
        immediates = [0, 1, 15, 31] if op in ("slli", "srli", "srai") else [-2048, -1, 0, 1, 2047]
        for a in edge:
            for b in immediates:
                lines.append(f"CHECK_I {op}, 0x{a:08x}, {b}, 0x{evaluate(base, a, b):08x}")
    for op in "beq bne blt bge bltu bgeu".split():
        for a, b in pairs[:36]:
            lines.append(f"CHECK_BRANCH {op}, 0x{a:08x}, 0x{b:08x}, {evaluate(op, a, b)}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    parser.add_argument("--seed", type=lambda x: int(x, 0), default=0xA57E)
    args = parser.parse_args()
    content = generate(args.seed)
    args.output.write_text(content)
    print(f"Generated {len(content.splitlines()) - 1} RV32IM vector groups, seed={args.seed}")


if __name__ == "__main__":
    main()
