#!/usr/bin/env python3
"""Generate the Q15 twiddle table for the fixed-point FFT workload.

Emits software/benchmarks/workload_fft_twiddle.h. The same table is recomputed
by scripts/workload_reference.py, so the firmware and the oracle agree exactly.
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path

N = 256
Q = 32767


def round_half_away(value: float) -> int:
    return int(math.floor(value + 0.5)) if value >= 0 else -int(math.floor(-value + 0.5))


def twiddles(n: int = N):
    rows = []
    for k in range(n // 2):
        angle = 2.0 * math.pi * k / n
        rows.append((round_half_away(math.cos(angle) * Q), round_half_away(-math.sin(angle) * Q)))
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("software/benchmarks/workload_fft_twiddle.h"))
    args = parser.parse_args()
    rows = twiddles()
    lines = [
        "// Generated by scripts/gen_fft_twiddle.py. Do not edit.",
        "#ifndef WORKLOAD_FFT_TWIDDLE_H",
        "#define WORKLOAD_FFT_TWIDDLE_H",
        "#include <stdint.h>",
        f"#define FFT_N {N}",
        f"#define FFT_TWIDDLE_COUNT {len(rows)}",
        f"static const int16_t fft_twiddle_re[{len(rows)}] = {{",
    ]
    for start in range(0, len(rows), 12):
        lines.append("    " + ", ".join(str(rows[i][0]) for i in range(start, min(start + 12, len(rows)))) + ",")
    lines.append("};")
    lines.append(f"static const int16_t fft_twiddle_im[{len(rows)}] = {{")
    for start in range(0, len(rows), 12):
        lines.append("    " + ", ".join(str(rows[i][1]) for i in range(start, min(start + 12, len(rows)))) + ",")
    lines.append("};")
    lines.append("#endif")
    lines.append("")
    args.output.write_text("\n".join(lines))
    print(f"wrote {args.output} ({len(rows)} twiddles)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
