#!/usr/bin/env python3
"""The MNIST MLP's weights transposed, for 20.4's batched NPU method (software/matrix/mnist.c, MNIST_METHOD 4):
fc1 as W1^T (784 x 32) and fc2 as W2^T (32 x 10), so a batch runs as images x W^T with the images read in
place. Stored reordered at build time, as 19.3 decided for CIFAR, in place of the original layout: the batched
firmware carries these and not phase11_model.h's, which would not fit beside them in 96 KiB. Written from
docs/results/phase11/model.json (its hash checked) to software/matrix/phase11_weights_t.h; `--check` compares
the file with what it would write."""
import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "software/matrix/phase11_weights_t.h"


def render() -> str:
    model = json.loads((ROOT / "docs/results/phase11/model.json").read_text())
    payload = json.dumps({k: v for k, v in model.items() if k != "hash"}, sort_keys=True).encode()
    if hashlib.sha256(payload).hexdigest() != model["hash"]:
        raise SystemExit("model.json's hash does not match its contents")
    lines = ["// Generated by scripts/gen_mnist_transposed.py from docs/results/phase11/model.json; do not edit.",
             f"// The frozen model's weights transposed (model hash {model['hash']}).",
             "#ifndef PHASE11_WEIGHTS_T_H", "#define PHASE11_WEIGHTS_T_H", "#include <stdint.h>"]
    for index, name in ((0, "phase11_fc1_weights_t"), (1, "phase11_fc2_weights_t")):
        layer = model["layers"][index]
        n_in, n_out, w = layer["in"], layer["out"], layer["weights"]
        t = [w[j * n_in + k] for k in range(n_in) for j in range(n_out)]          # (k, j) = W(j, k)
        lines.append(f"static const int8_t {name}[{n_in * n_out}] __attribute__((aligned(64))) = {{")
        for i in range(0, len(t), 24):
            lines.append("    " + ", ".join(str(v) for v in t[i:i + 24]) + ",")
        lines.append("};")
    lines.append("#endif")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        same = OUT.exists() and OUT.read_text() == text
        print(f"{'PASS' if same else 'FAIL'}: {OUT.relative_to(ROOT)} is what the model gives")
        return 0 if same else 1
    OUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
