#!/usr/bin/env python3
"""Export a Phase 11 model artifact into firmware C headers.

Re-runs the independent integer reference, then emits the INT8 weights, the
requantized biases, the fixed-point multipliers and the retained quantized test
subset as C headers plus a hash-bound manifest. The firmware includes these
headers; no floating point or training code reaches the board.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import phase11_reference as reference


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def c_int8(name: str, values: list[int], per_line: int = 16) -> str:
    lines = [f"static const int8_t {name}[{len(values)}] = {{"]
    for start in range(0, len(values), per_line):
        chunk = ", ".join(str(v) for v in values[start:start + per_line])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def c_int32(name: str, values: list[int], per_line: int = 12) -> str:
    lines = [f"static const int32_t {name}[{len(values)}] = {{"]
    for start in range(0, len(values), per_line):
        chunk = ", ".join(str(v) for v in values[start:start + per_line])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def c_u8(name: str, values: list[int], per_line: int = 16) -> str:
    lines = [f"static const uint8_t {name}[{len(values)}] = {{"]
    for start in range(0, len(values), per_line):
        chunk = ", ".join(str(v) for v in values[start:start + per_line])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("model", type=Path)
    parser.add_argument("--header-dir", type=Path, default=Path("software/benchmarks"))
    parser.add_argument("--manifest", type=Path, default=Path("build/phase11/export.json"))
    args = parser.parse_args()

    result = reference.reference(args.model)
    model = json.loads(args.model.read_text())
    fc1, fc2 = model["layers"]
    test = model["test"]

    header = [
        "// Generated by scripts/phase11_export.py. Do not edit.",
        f"// model hash {model['hash']}",
        "#ifndef PHASE11_MODEL_H",
        "#define PHASE11_MODEL_H",
        "#include <stdint.h>",
        "",
        f"#define PHASE11_FC1_IN {fc1['in']}u",
        f"#define PHASE11_FC1_OUT {fc1['out']}u",
        f"#define PHASE11_FC2_IN {fc2['in']}u",
        f"#define PHASE11_FC2_OUT {fc2['out']}u",
        f"#define PHASE11_FC1_MULT {fc1['requant']['mult']}",
        f"#define PHASE11_FC1_SHIFT {fc1['requant']['shift']}",
        f"#define PHASE11_FC2_MULT {fc2['requant']['mult']}",
        f"#define PHASE11_FC2_SHIFT {fc2['requant']['shift']}",
        "",
        c_int8("phase11_fc1_weights", fc1["weights"]),
        "",
        c_int8("phase11_fc2_weights", fc2["weights"]),
        "",
        c_int32("phase11_fc1_bias_q", fc1["bias_q"]),
        "",
        c_int32("phase11_fc2_bias_q", fc2["bias_q"]),
        "",
        "#endif",
        "",
    ]
    images_header = [
        "// Generated by scripts/phase11_export.py. Do not edit.",
        f"// model hash {model['hash']}",
        "#ifndef PHASE11_IMAGES_H",
        "#define PHASE11_IMAGES_H",
        "#include <stdint.h>",
        "",
        f"#define PHASE11_TEST_COUNT {len(test['labels'])}u",
        "",
        c_int8("phase11_test_images", test["images"]),
        "",
        c_u8("phase11_test_labels", test["labels"]),
        "",
        c_u8("phase11_test_classes", test["reference_classes"]),
        "",
        c_int8("phase11_test_logits", [value for row in test["reference_logits"] for value in row]),
        "",
        "#endif",
        "",
    ]

    model_header = args.header_dir / "phase11_model.h"
    images_header_path = args.header_dir / "phase11_images.h"
    model_header.write_text("\n".join(header))
    images_header_path.write_text("\n".join(images_header))

    manifest = {
        "schema": "aster.phase11.export.v1",
        "model_hash": model["hash"],
        "reference": result,
        "headers": {
            "phase11_model.h": sha256(model_header),
            "phase11_images.h": sha256(images_header_path),
        },
        "test_count": len(test["labels"]),
    }
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    print(f"PASS: exported {model_header} and {images_header_path} "
          f"({manifest['test_count']} images, reference {result['accuracy']:.4f})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
