#!/usr/bin/env python3
"""Phase 15 ASIC flow driver.

SystemVerilog is converted to Verilog with sv2v (Yosys cannot parse several
constructs Aster uses, such as ``return`` inside a function), then LibreLane
runs the SKY130 Classic flow on the converted netlist.

    python3 scripts/run_asic.py                      # full Classic flow
    python3 scripts/run_asic.py --to Yosys.Synthesis # stop after synthesis

The ROM init path inside the RTL is relative, so the flow always runs from the
repository root.
"""
import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASIC = ROOT / "asic" / "sky130"
BUILD = ASIC / "build"

SV2V = os.environ.get("SV2V", str(Path.home() / "tools" / "sv2v" / "sv2v-Linux" / "sv2v"))
LIBRELANE = os.environ.get("LIBRELANE", str(Path.home() / "tools" / "librelane-venv" / "bin" / "librelane"))

RTL = [
    "vendor/picorv32/picorv32.v",
    "rtl/core/aster_picorv32.sv",
    "rtl/cache/aster_l1_cache.sv",
    "rtl/memory/aster_rom.sv",
    "rtl/memory/aster_ram.sv",
    "rtl/memory/aster_sram_macro.sv",
    "rtl/peripherals/aster_uart.sv",
    "rtl/peripherals/aster_perf_counters.sv",
    "rtl/core/aster_hart.sv",
    "rtl/soc/aster_minimal.sv",
    "rtl/peripherals/aster_uart_tx.sv",
    "asic/sky130/aster_asic.sv",
]

DEFINES = ["RISCV_FORMAL", "SYNTHESIS", "ASTER_ROM_IMAGE"]

# A ROM built from power-up-initialised flops cannot work on silicon, and the
# synthesis tools drop the initialiser when the memory is mapped through ABC.
# Instead the driver bakes the firmware into an explicit combinational ROM.
ROM_INIT = ROOT / "asic" / "sky130" / "rom" / "hello_2k.hex"


def generate_rom_image():
    """Emit build/rom_image.v with the firmware as combinational constants."""
    words = []
    for line in ROM_INIT.read_text().splitlines():
        line = line.strip()
        words.append(int(line, 16) if line else 0)
    output = BUILD / "rom_image.v"
    lines = [
        "// Generated by scripts/run_asic.py from",
        f"// {ROM_INIT.relative_to(ROOT)} - do not edit.",
        "module aster_asic_rom_image (",
        "    input  wire [31:0] addr,",
        "    output reg  [31:0] data",
        ");",
        "    always @(*) begin",
        "        case (addr)",
    ]
    for index, word in enumerate(words):
        lines.append(f"            32'd{index}: data = 32'h{word:08x};")
    lines += [
        "            default: data = 32'h00000000;",
        "        endcase",
        "    end",
        "endmodule",
        "",
    ]
    output.write_text("\n".join(lines))
    print(f"rom image -> {output.relative_to(ROOT)} ({len(words)} words)", flush=True)
    return output


def convert():
    BUILD.mkdir(parents=True, exist_ok=True)
    generate_rom_image()
    output = BUILD / "aster_asic.v"
    command = [SV2V]
    for define in DEFINES:
        command += ["-D", define]
    command += [str(ROOT / path) for path in RTL]
    print(f"sv2v -> {output.relative_to(ROOT)}", flush=True)
    with output.open("w") as stream:
        subprocess.run(command, cwd=ROOT, stdout=stream, check=True)
    strip_comb_guards(output)
    return output


def strip_comb_guards(path):
    """Drop sv2v's ``if (_sv2v_0) ;`` always_comb guard.

    sv2v emits this empty statement to preserve always_comb's time-zero
    evaluation. It is a no-op for synthesis but Yosys' Verilog parser rejects
    an empty statement, so remove the pair.
    """
    lines = path.read_text().splitlines(keepends=True)
    kept = []
    index = 0
    while index < len(lines):
        if "_sv2v_0" in lines[index] and index + 1 < len(lines) and lines[index + 1].strip() == ";":
            index += 2
            continue
        kept.append(lines[index])
        index += 1
    path.write_text("".join(kept))


def pdk_macro_files(pdk_root):
    """Locate the SRAM macro views inside the ciel PDK install.

    LibreLane selects a PDK version itself, so search every installed version
    and prefer the newest one that carries the macro.
    """
    name = "sky130_sram_2kbyte_1rw1r_32x512_8"
    candidates = sorted(
        Path(pdk_root).glob("ciel/sky130/versions/*/sky130A/libs.ref/sky130_sram_macros"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    for root in candidates:
        lef = root / "lef" / f"{name}.lef"
        gds = root / "gds" / f"{name}.gds"
        mag = root / "maglef" / f"{name}.mag"
        libs = sorted((root / "lib").glob(f"{name}_*.lib"))
        if lef.is_file() and gds.is_file() and libs:
            return lef, libs, gds, mag
    raise SystemExit(f"no {name} macro views found under {pdk_root}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pdk-root", default=os.environ.get("PDK_ROOT", str(Path.home() / ".ciel")))
    parser.add_argument("--to", default=None, help="stop at this LibreLane step id")
    parser.add_argument("--run-tag", default=None)
    parser.add_argument("--skip-convert", action="store_true")
    parser.add_argument("librelane_args", nargs="*")
    args = parser.parse_args()

    if not args.skip_convert:
        convert()
    else:
        generate_rom_image()

    lef, libs, gds, mag = pdk_macro_files(args.pdk_root)

    command = [LIBRELANE, "--docker-no-tty", "--dockerized", "--pdk-root", args.pdk_root]
    if args.to:
        command += ["-T", args.to]
    if args.run_tag:
        command += ["--run-tag", args.run_tag]
    command += [
        "--override-config", "EXTRA_LEFS=" + str(lef),
        "--override-config", "EXTRA_LIBS=" + ",".join(str(lib) for lib in libs),
        "--override-config", "EXTRA_GDS=" + str(gds),
    ]
    if mag.is_file():
        command += ["--override-config", "MAGIC_DRC_MAGLEFS=" + str(mag)]
    command += args.librelane_args
    command += [str(ASIC / "config.json")]

    print("librelane:", " ".join(command), flush=True)
    return subprocess.run(command, cwd=ROOT).returncode


if __name__ == "__main__":
    sys.exit(main())
